steps:
- name: 'gcr.io/cloud-builders/git'
  args: [ 'config',  '--global', 'init.defaultBranch', 'master']
- name: gcr.io/cloud-builders/docker
  args: [build, '.', -t, us-west1-docker.pkg.dev/$PROJECT_ID/gcloud-lite/gcloud-go]
- name: gcr.io/cloud-builders/docker
  args: [create, --name, binary_build, us-west1-docker.pkg.dev/$PROJECT_ID/gcloud-lite/gcloud-go]
- name: alpine
  args: [mkdir, -p, /workspace/build/bin/]
- name: gcr.io/cloud-builders/docker
  args: [cp, binary_build:/gcloud-go, /workspace/build/bin/]
- name: alpine
  args: [tar,-zcf,build/gcloud-go.tgz,-C,build/bin,'.']
- name: us-west1-docker.pkg.dev/$PROJECT_ID/tonym-us/github-release
  args: [ tonymet, gcloud-go, build/gcloud-go.tgz, 'gcloud-go cli release']
  secretEnv: [GH_TOKEN]
  env:
    - 'COMMIT=$SHORT_SHA'
    - 'SHA=$COMMIT_SHA'
images:
- us-west1-docker.pkg.dev/$PROJECT_ID/gcloud-lite/gcloud-go
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/GH_TOKEN/versions/1
    env: GH_TOKEN
tags: [latest]
options:
  logging: CLOUD_LOGGING_ONLY