steps:
- name: gcr.io/cloud-builders/docker
  args: [build, '.', -t, us-west1-docker.pkg.dev/$PROJECT_ID/gcloud-lite/gcloud-go]
- name: gcr.io/cloud-builders/docker
  args: [create, --name, binary_build, us-west1-docker.pkg.dev/$PROJECT_ID/gcloud-lite/gcloud-go]
- name: alpine
  args: [mkdir, -p, /workspace/build/bin/]
- name: gcr.io/cloud-builders/docker
  args: [cp, binary_build:/gcloud-go, /workspace/build/bin/]
- name: gcr.io/cloud-builders/docker
  args: ['build', '.', '-f', 'Dockerfile-release',  '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/tonym-us/gcloud-go-release']
- name: us-west1-docker.pkg.dev/$PROJECT_ID/tonym-us/gcloud-go-release
  secretEnv: [GH_TOKEN]
  env:
    - 'COMMIT=$SHORT_SHA'
    - 'SHA=$COMMIT_SHA'
images:
- us-west1-docker.pkg.dev/$PROJECT_ID/gcloud-lite/gcloud-go
- us-west1-docker.pkg.dev/$PROJECT_ID/tonym-us/gcloud-go-release
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/GH_TOKEN/versions/1
    env: GH_TOKEN
tags: [latest]
options:
  logging: CLOUD_LOGGING_ONLY